/**
 * @generated
 * @file BlogItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link BlogItem}
 */
export type BlogItemProps = {
  authorName?: React.ReactNode;
  authorPicture?: string;
  mainImage?: string;
  name?: React.ReactNode;
  postSummary?: React.ReactNode;
  primaryCategoryName?: React.ReactNode;
  readMinutes?: React.ReactNode;
  updatedOn?: React.ReactNode;
};

/**
 * BlogItem
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function BlogItem({
  authorName = "This is some text inside of a div block.",
  authorPicture = "",
  mainImage = "",
  name = "Heading",
  postSummary = "This is some text inside of a div block.",
  primaryCategoryName = "This is some text inside of a div block.",
  readMinutes = "This is some text inside of a div block.",
  updatedOn = "This is some text inside of a div block.",
}: BlogItemProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"blog-item"} tag={"div"}>
        <Link
          block={"inline"}
          button={false}
          className={"blog-image-link"}
          options={{
            href: "#",
          }}
        >
          <Block className={"blog-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              height={"auto"}
              loading={"lazy"}
              src={mainImage}
              width={"auto"}
            />
          </Block>
        </Link>
        <Block className={"blog-item-content"} tag={"div"}>
          <Link
            block={"inline"}
            button={false}
            className={"button-link is-small"}
            options={{
              href: "#",
            }}
          >
            <Block className={"blog-category-text"} tag={"div"}>
              {primaryCategoryName}
            </Block>
          </Link>
          <Link
            block={"inline"}
            button={false}
            className={"blog-title-link"}
            options={{
              href: "#",
            }}
          >
            <Heading className={"heading-style-h5"} tag={"h3"}>
              {name}
            </Heading>
          </Link>
          <Block className={"text-style-regular"} tag={"div"}>
            {postSummary}
          </Block>
          <Block className={"blog-author-wrapper"} tag={"div"}>
            <Block className={"blog-author-image-wrapper-2"} tag={"div"}>
              <Image
                alt={""}
                className={"blog-author-image"}
                height={"auto"}
                loading={"lazy"}
                src={authorPicture}
                width={"auto"}
              />
            </Block>
            <Block className={"blog-details-wrapper"} tag={"div"}>
              <Block className={"text-style-regular is-light"} tag={"div"}>
                {authorName}
              </Block>
              <Block className={"blog-date-wrapper"} tag={"div"}>
                <Block className={"text-style-small is-light"} tag={"div"}>
                  {updatedOn}
                </Block>
                <Block className={"blog-text-divider"} tag={"div"}>
                  {"•"}
                </Block>
                <Block className={"text-style-small is-light"} tag={"div"}>
                  {readMinutes}
                </Block>
                <Block className={"text-style-small is-light"} tag={"div"}>
                  {"min read"}
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
