/**
 * @generated
 * @file BookAWalkthrough (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link BookAWalkthrough}
 */
export type BookAWalkthroughProps = {
  description?: React.ReactNode;
  formLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  linkText?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * BookAWalkthrough
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function BookAWalkthrough({
  description = "We’ll begin with a virtual walkthrough to see how the space lives and breathes today, noticing what already works and where things feel misaligned. Then we’ll talk through your goals, constraints, and ideas, and map thoughtful next steps grounded in your real environment.",

  formLink = {
    href: "#26e3fff6-7f60-8d55-48a5-16f01cdbcaf5",
  },

  linkText = "General Inquiries",
  title = "Book a Virtual Walkthrough",
}: BookAWalkthroughProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"book-component"} tag={"div"}>
        <Block className={"book-content"} tag={"div"}>
          <Heading className={"heading-style-h1"} tag={"h2"}>
            {title}
          </Heading>
          <Paragraph className={"text-style-regular"}>{description}</Paragraph>
          <Block className={"button-group"} tag={"div"}>
            <Link
              block={"inline"}
              button={false}
              className={"button-link"}
              options={formLink}
            >
              <Block className={"button-link-text"} tag={"div"}>
                {linkText}
              </Block>
              <HtmlEmbed
                className={"button-link-icon"}
                content={
                  '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M6 3L11 8L6 13" stroke="CurrentColor" stroke-width="1.5"/>\n</svg>'
                }
              />
            </Link>
          </Block>
        </Block>
        <Block className={"calendar-embed-wrapper"} tag={"div"}>
          <HtmlEmbed
            content={
              '<!-- Calendly inline widget begin -->\n<div class="calendly-inline-widget" data-url="https://calendly.com/hosanna-mcgowen-webflow/30min?hide_event_type_details=1&hide_gdpr_banner=1&background_color=a39f97&text_color=111111&primary_color=423a31" style="min-width:320px;height:700px;"></div>\n<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>\n<!-- Calendly inline widget end -->'
            }
          />
        </Block>
      </Block>
    </div>
  );
}
