/**
 * @generated
 * @file ButtonPrimary (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtonPrimary}
 */
export type ButtonPrimaryProps = {
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
};

/**
 * ButtonPrimary
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function ButtonPrimary({
  link = {
    href: "#",
  },

  text = "Browse Atmospheres",
}: ButtonPrimaryProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        button={true}
        className={"button-primary"}
        id={"w-node-_8e1e79ff-092a-c3df-5501-2b3a20f841ec-20f841ec"}
        options={link}
      >
        {text}
      </Link>
    </div>
  );
}
