/**
 * @generated
 * @file ContactForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import FormBlockLabel from "./webflow_modules/Form/components/FormBlockLabel";
import FormButton from "./webflow_modules/Form/components/FormButton";
import FormCheckboxInput from "./webflow_modules/Form/components/FormCheckboxInput";
import FormCheckboxWrapper from "./webflow_modules/Form/components/FormCheckboxWrapper";
import FormErrorMessage from "./webflow_modules/Form/components/FormErrorMessage";
import FormForm from "./webflow_modules/Form/components/FormForm";
import FormInlineLabel from "./webflow_modules/Form/components/FormInlineLabel";
import FormSuccessMessage from "./webflow_modules/Form/components/FormSuccessMessage";
import FormTextarea from "./webflow_modules/Form/components/FormTextarea";
import FormTextInput from "./webflow_modules/Form/components/FormTextInput";
import FormWrapper from "./webflow_modules/Form/components/FormWrapper";
import Grid from "./webflow_modules/Layout/components/Grid";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import NotSupported from "./webflow_modules/Builtin/components/NotSupported";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link ContactForm}
 */
export type ContactFormProps = {};

/**
 * ContactForm
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Animation`
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function ContactForm({}: ContactFormProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Section className={"section-contact"} tag={"section"}>
          <Block className={"padding-global"} tag={"div"}>
            <Block className={"container-large"} tag={"div"}>
              <Block className={"padding-section-large"} tag={"div"}>
                <Grid className={"contact-component"} tag={"div"}>
                  <Block
                    className={"contact-content"}
                    id={"w-node-_0c72adef-89bb-b796-5878-9e469db25608-9db25602"}
                    tag={"div"}
                  >
                    <Block className={"contact-heading-wrapper"} tag={"div"}>
                      <Block className={"text-style-subheading"} tag={"div"}>
                        {"CONTACTUS"}
                      </Block>
                      <Heading className={"heading-style-h2"} tag={"h2"}>
                        {"Join us at the table"}
                      </Heading>
                      <Paragraph className={"text-style-medium"}>
                        {
                          "Tell us about your space and we’ll help you shape the atmosphere."
                        }
                      </Paragraph>
                    </Block>
                    <FormWrapper className={"contact-form-block"}>
                      <FormForm
                        className={"contact-form"}
                        data-name={"Contact Form - Mise Lab"}
                        id={"wf-form-Contact-Form-Mise-Lab"}
                        method={"get"}
                        name={"wf-form-Contact-Form---Mise-Lab"}
                      >
                        <Block
                          className={"contact-form-field-wrapper"}
                          tag={"div"}
                        >
                          <FormBlockLabel
                            className={"field-label"}
                            htmlFor={"Contact-Name"}
                            id={"Contact-Name-Label"}
                          >
                            {"Name"}
                          </FormBlockLabel>
                          <FormTextInput
                            autoFocus={false}
                            className={"form-input"}
                            data-name={"Contact-Name"}
                            disabled={false}
                            maxLength={256}
                            name={"Contact-Name"}
                            required={true}
                            type={"text"}
                          />
                        </Block>
                        <Block
                          className={"contact-form-field-wrapper"}
                          tag={"div"}
                        >
                          <FormBlockLabel
                            className={"field-label"}
                            htmlFor={"Contact-Company-Email"}
                          >
                            {"Company Email"}
                          </FormBlockLabel>
                          <FormTextInput
                            autoFocus={false}
                            className={"form-input"}
                            data-name={"Contact-Company-Email"}
                            disabled={false}
                            maxLength={256}
                            name={"Contact-Company-Email"}
                            required={true}
                            type={"email"}
                          />
                        </Block>
                        <Block
                          className={"contact-form-field-wrapper"}
                          tag={"div"}
                        >
                          <FormBlockLabel
                            className={"field-label"}
                            htmlFor={"Contact-Needs-Message"}
                            id={"Contact-Needs-Label"}
                          >
                            {"Space & Needs"}
                          </FormBlockLabel>
                          <FormTextarea
                            autoFocus={false}
                            className={"form-text-area"}
                            data-name={"Contact-Needs-Message"}
                            maxLength={5000}
                            name={"Contact-Needs-Message"}
                            placeholder={
                              "Tell us about your space and the atmosphere you want to create."
                            }
                            required={true}
                          />
                        </Block>
                        <FormCheckboxWrapper className={"form-checkbox"}>
                          <FormCheckboxInput
                            checked={false}
                            className={"form-checkbox-icon"}
                            customClassName={
                              "w-checkbox-input--inputType-custom"
                            }
                            data-name={"Contact-Terms-Checkbox"}
                            form={{
                              type: "checkbox-input",
                              name: "Contact-Terms-Checkbox",
                            }}
                            id={"Contact-Terms-Checkbox"}
                            inputType={"custom"}
                            name={"Contact-Terms-Checkbox"}
                            required={true}
                            type={"checkbox"}
                          />
                          <FormInlineLabel
                            className={"checkbox-label-small"}
                          >
                            {"I accept the "}
                            <Link
                              button={false}
                              className={"text-style-link"}
                              options={{
                                href: "#",
                              }}
                            >
                              {"Terms"}
                            </Link>
                          </FormInlineLabel>
                        </FormCheckboxWrapper>
                        <Block
                          className={"contact-button-wrapper"}
                          id={
                            "w-node-_0c72adef-89bb-b796-5878-9e469db25624-9db25602"
                          }
                          tag={"div"}
                        >
                          <FormButton
                            className={"button-primary"}
                            data-wait={
                              "Sharing your message with the Mise Lab team..."
                            }
                            id={
                              "w-node-_0c72adef-89bb-b796-5878-9e469db25625-9db25602"
                            }
                            type={"submit"}
                            value={"Submit"}
                          />
                        </Block>
                      </FormForm>
                      <FormSuccessMessage className={"_w-form-done"}>
                        <NotSupported _atom={"Animation"} />
                        <Block className={"success-text"} tag={"div"}>
                          {
                            "Thank you! Your submission has been received! You'll hear back from the Mise Lab team within two business days."
                          }
                        </Block>
                      </FormSuccessMessage>
                      <FormErrorMessage className={"error-message"}>
                        <Block className={"error-text"} tag={"div"}>
                          {
                            "Oops! Something went wrong. Please double-check your entries and try again."
                          }
                        </Block>
                      </FormErrorMessage>
                    </FormWrapper>
                  </Block>
                  <Block className={"contact-image-wrapper"} tag={"div"}>
                    <Image
                      alt={
                        "Several place settings along a bar top seating area."
                      }
                      className={"contact-image"}
                      height={"auto"}
                      loading={"lazy"}
                      src={
                        "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee5c_michael-wave-GrPm7g3crwQ-unsplash.webp"
                      }
                      width={"auto"}
                    />
                  </Block>
                </Grid>
              </Block>
            </Block>
          </Block>
        </Section>
      </Section>
    </div>
  );
}
