/**
 * @generated
 * @file FaQs (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import NotSupported from "./webflow_modules/Builtin/components/NotSupported";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link FaQs}
 */
export type FaQsProps = {
  faqAnswerText?: React.ReactNode;
  faqQuestionText?: React.ReactNode;
};

/**
 * FaQs
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Animation`
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function FaQs({
  faqAnswerText = "We collaborate with independent restaurateurs, hospitality groups, cafes, bakeries, tasting rooms, and boutique hotels that value thoughtful design and lasting atmosphere. ",
  faqQuestionText = "What types of spaces do you partner with?",
}: FaQsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"faq-component"} tag={"div"}>
        <Block className={"section-heading-wrapper is-centered"} tag={"div"}>
          <Heading className={"heading-style-h2"} tag={"h2"}>
            {"FAQs"}
          </Heading>
          <Paragraph className={"text-style-medium"}>
            {"A closer look at what we offer and how each partnership unfolds."}
          </Paragraph>
        </Block>
        <Block className={"faq-heading-wrapper"} tag={"div"} />
        <Block className={"faq-list"} tag={"div"}>
          <Block className={"faq-accordion"} tag={"div"}>
            <Block className={"faq-question"} tag={"div"}>
              <Block className={"faq-question-text"} tag={"div"}>
                {faqQuestionText}
              </Block>
              <Block className={"faq-icon-wrapper"} tag={"div"}>
                <NotSupported _atom={"Animation"} />
              </Block>
            </Block>
            <Block className={"faq-answer-1"} tag={"div"}>
              <Block className={"faq-answer-wrapper"} tag={"div"}>
                <Paragraph className={"text-style-regular"}>
                  {faqAnswerText}
                </Paragraph>
              </Block>
            </Block>
          </Block>
          <Block className={"faq-accordion"} tag={"div"}>
            <Block className={"faq-question"} tag={"div"}>
              <Block className={"faq-question-text"} tag={"div"}>
                {
                  "Can The Mise Lab work with my existing designer or architect?"
                }
              </Block>
              <Block className={"faq-icon-wrapper"} tag={"div"}>
                <NotSupported _atom={"Animation"} />
              </Block>
            </Block>
            <Block className={"faq-answer-2"} tag={"div"}>
              <Block className={"faq-answer-wrapper"} tag={"div"}>
                <Paragraph className={"text-style-regular"}>
                  {
                    "Yes. We often collaborate with in-house teams and external partners, integrating our systems and materials into their broader design approach to ensure cohesion and consistency."
                  }
                </Paragraph>
              </Block>
            </Block>
          </Block>
          <Block className={"faq-accordion"} tag={"div"}>
            <Block className={"faq-question"} tag={"div"}>
              <Block className={"faq-question-text"} tag={"div"}>
                {"How long does a typical project take?"}
              </Block>
              <Block className={"faq-icon-wrapper"} tag={"div"}>
                <NotSupported _atom={"Animation"} />
              </Block>
            </Block>
            <Block className={"faq-answer-3"} tag={"div"}>
              <Block className={"faq-answer-wrapper"} tag={"div"}>
                <Paragraph className={"text-style-regular"}>
                  {
                    "Timelines vary based on scope and complexity, but most full atmosphere projects move through discovery, selection, and prototype stages within 4-6 weeks. From there, we provide direction and documentation to help your team move smoothly into installation and opening."
                  }
                </Paragraph>
              </Block>
            </Block>
          </Block>
          <Block className={"faq-accordion"} tag={"div"}>
            <Block className={"faq-question"} tag={"div"}>
              <Block className={"faq-question-text"} tag={"div"}>
                {
                  "Can you help refine an existing space rather than start from scratch?"
                }
              </Block>
              <Block className={"faq-icon-wrapper"} tag={"div"}>
                <NotSupported _atom={"Animation"} />
              </Block>
            </Block>
            <Block className={"faq-answer-4"} tag={"div"}>
              <Block className={"faq-answer-wrapper"} tag={"div"}>
                <Paragraph className={"text-style-regular"}>
                  {
                    "Yes. Many projects begin with an existing layout or palette. We can help reframe, refine, or layer in new elements to bring clarity and cohesion to what you already have."
                  }
                </Paragraph>
              </Block>
            </Block>
          </Block>
          <Block className={"faq-accordion"} tag={"div"}>
            <Block className={"faq-question"} tag={"div"}>
              <Block className={"faq-question-text"} tag={"div"}>
                {"What kind of ongoing support do you offer?"}
              </Block>
              <Block className={"faq-icon-wrapper"} tag={"div"}>
                <NotSupported _atom={"Animation"} />
              </Block>
            </Block>
            <Block className={"faq-answer-5"} tag={"div"}>
              <Block className={"faq-answer-wrapper"} tag={"div"}>
                <Paragraph className={"text-style-regular"}>
                  {
                    "Once the space is complete, we reconnect after the first couple of weeks to see how it feels in daily use. From there, we check in seasonally, offering adjustments to help you stay fresh. You can also reach out to us any anytime. We build lifelong partnerships, supporting your space as it continues to evolve."
                  }
                </Paragraph>
              </Block>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
