/**
 * @generated
 * @file Gallery (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import NotSupported from "./webflow_modules/Builtin/components/NotSupported";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import SliderArrow from "./webflow_modules/Slider/components/SliderArrow";
import SliderMask from "./webflow_modules/Slider/components/SliderMask";
import SliderNav from "./webflow_modules/Slider/components/SliderNav";
import SliderSlide from "./webflow_modules/Slider/components/SliderSlide";
import SliderWrapper from "./webflow_modules/Slider/components/SliderWrapper";

/**
 * Props for {@link Gallery}
 */
export type GalleryProps = {
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
  text?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * Gallery
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Lightbox Wrapper`
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function Gallery({
  image1 = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee4d_decima-athens-PisnUZWdsms-unsplash.webp",
  image2 = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee48_amin-ramezani-afOvuzIgxPU-unsplash.webp",
  image3 = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee4b_dinesh-ramaswamy-p-sEkj6-hAM-unsplash.webp",
  image4 = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee58_mustafa-fatemi-RH7aAPxQsFE-unsplash.webp",
  image5 = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee4f_duc-van-qgrxyu2fr7g-unsplash_smaller.webp",
  text = "A taste of what’s waiting in the space, from seasonal atmospheres to tactile details.",
  title = "Inside the Showroom",
}: GalleryProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"gallery-component"} tag={"div"}>
        <Block className={"section-heading-wrapper"} tag={"div"}>
          <Heading className={"heading-style-h2"} tag={"h2"}>
            {title}
          </Heading>
          <Paragraph className={"text-style-regular"}>{text}</Paragraph>
        </Block>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={false}
          className={"gallery-slider"}
          data-animation={"slide"}
          data-duration={"500"}
          data-infinite={"1"}
          delay={4000}
          disableSwipe={false}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"gallery13_slider"}
          infinite={false}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"gallery-mask"}>
            <SliderSlide className={"gallery-slide"} tag={"div"}>
              <NotSupported _atom={"Lightbox Wrapper"} />
            </SliderSlide>
            <SliderSlide className={"gallery-slide"} tag={"div"}>
              <NotSupported _atom={"Lightbox Wrapper"} />
            </SliderSlide>
            <SliderSlide className={"gallery-slide"} tag={"div"}>
              <NotSupported _atom={"Lightbox Wrapper"} />
            </SliderSlide>
            <SliderSlide className={"gallery-slide"} tag={"div"}>
              <NotSupported _atom={"Lightbox Wrapper"} />
            </SliderSlide>
            <SliderSlide className={"gallery-slide"} tag={"div"}>
              <NotSupported _atom={"Lightbox Wrapper"} />
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"gallery-arrow-left"} dir={"left"}>
            <HtmlEmbed
              className={"gallery-arrow-icon"}
              content={
                '<svg width=" 100%" height=" 100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M5.81066 12.7499L12.5303 19.4696L11.4697 20.5303L2.93934 11.9999L11.4697 3.46961L12.5303 4.53027L5.81066 11.2499L20 11.2499L20 12.7499L5.81066 12.7499Z" fill="currentColor"/>\n</svg>'
              }
            />
          </SliderArrow>
          <SliderArrow className={"gallery-arrow-right"} dir={"right"}>
            <HtmlEmbed
              className={"gallery-arrow-icon"}
              content={
                '<svg width=" 100%" height=" 100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M18.1893 11.2501L11.4697 4.53039L12.5303 3.46973L21.0607 12.0001L12.5303 20.5304L11.4697 19.4697L18.1893 12.7501H4V11.2501H18.1893Z" fill="currentColor"/>\n</svg>'
              }
            />
          </SliderArrow>
          <SliderNav className={"gallery-slider-nav"} />
        </SliderWrapper>
      </Block>
    </div>
  );
}
