/**
 * @generated
 * @file Hero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Hero}
 *
 * Two-column hero: heading and paragraph on the left, image on the right, dark background.
 */
export type HeroProps = {};

/**
 * Hero
 *
 * Two-column hero: heading and paragraph on the left, image on the right, dark background.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function Hero({}: HeroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section className={"hero-section-bg"} tag={"section"}>
        <Block className={"padding-global"} tag={"div"}>
          <Block tag={"div"}>
            <Block className={"padding-section-large"} tag={"div"}>
              <Block className={"hero-section-page"} tag={"div"}>
                <Block className={"hero-content-page"} tag={"div"}>
                  <Heading className={"heading-style-h1"} tag={"h1"}>
                    {"Find Your Style"}
                  </Heading>
                  <Paragraph className={"text-style-medium"}>
                    {
                      "From refined and elegant to breezy and rustic, we've got a style for every space. Answer a few quick questions to find the one that matches your atmosphere."
                    }
                  </Paragraph>
                </Block>
                <Block className={"hero-image-wrapper"} tag={"div"}>
                  <Image
                    alt={
                      "A place setting with two nested white plates on a neutral linen tablecloth."
                    }
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee4a_jean-marc-vieregge-Q9IGFfztBe4-unsplash.webp"
                    }
                    width={"auto"}
                  />
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
