/**
 * @generated
 * @file MailingListCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import FormBlockLabel from "./webflow_modules/Form/components/FormBlockLabel";
import FormButton from "./webflow_modules/Form/components/FormButton";
import FormErrorMessage from "./webflow_modules/Form/components/FormErrorMessage";
import FormForm from "./webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "./webflow_modules/Form/components/FormSuccessMessage";
import FormTextInput from "./webflow_modules/Form/components/FormTextInput";
import FormWrapper from "./webflow_modules/Form/components/FormWrapper";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link MailingListCta}
 */
export type MailingListCtaProps = {};

/**
 * MailingListCta
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function MailingListCta({}: MailingListCtaProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section className={"section-mailer-cta"} tag={"section"}>
        <Block className={"padding-global"} tag={"div"}>
          <Block className={"container-small"} tag={"div"}>
            <Block className={"padding-section-large"} tag={"div"}>
              <Block className={"mailer-component"} tag={"div"}>
                <Block className={"section-heading-wrapper"} tag={"div"}>
                  <Heading className={"heading-style-h1"} tag={"h2"}>
                    {"Mise Lab Mailing List"}
                  </Heading>
                  <Paragraph className={"text-style-regular"}>
                    {
                      "Be the first to hear about new seasonal atmospheres, evolving styles, studio updates, blog posts, project stories, and special offers. Delivered with intention, not frequency."
                    }
                  </Paragraph>
                </Block>
                <FormWrapper className={"cta-form-block"}>
                  <FormForm
                    className={"cta-form"}
                    data-name={"Mailing list CTA form"}
                    id={"wf-form-Mailing-list-CTA-form"}
                    method={"get"}
                    name={"wf-form-Mailing-list-CTA-form"}
                  >
                    <Block className={"wrapper-cta-form"} tag={"div"}>
                      <FormTextInput
                        autoFocus={false}
                        className={"form-input"}
                        data-name={"Mailing-List-Email"}
                        disabled={false}
                        id={"Mailing-List-Email"}
                        maxLength={256}
                        name={"Mailing-List-Email"}
                        placeholder={"Enter your company email."}
                        required={true}
                        type={"email"}
                      />
                      <FormButton
                        className={"button-tertiary"}
                        data-wait={"Confirming your email..."}
                        type={"submit"}
                        value={"Sign Up"}
                      />
                    </Block>
                  </FormForm>
                  <FormSuccessMessage className={"success-text"}>
                    <Block className={"success-text"} tag={"div"}>
                      {"Thank you for joining the Mise Lab mailing list!"}
                    </Block>
                  </FormSuccessMessage>
                  <FormErrorMessage className={"error-text"}>
                    <Block className={"error-text"} tag={"div"}>
                      {"Oops! Please enter a valid email address."}
                    </Block>
                  </FormErrorMessage>
                </FormWrapper>
                <Block className={"text-style-tiny"} tag={"div"}>
                  {
                    "By clicking Sign Up you're confirming that you agree with our "
                  }
                  <Link
                    button={false}
                    className={"button-link is-tiny"}
                    options={{
                      href: "#",
                    }}
                  >
                    {"Terms and Conditions."}
                  </Link>
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
