/**
 * @generated
 * @file TestimonialCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link TestimonialCard}
 */
export type TestimonialCardProps = {
  avatarImage?: string;
  jobTitleText?: React.ReactNode;
  nameText?: React.ReactNode;
  testimonialText?: React.ReactNode;
};

/**
 * TestimonialCard
 *
 * @see {@link https://the-mise-lab-7817e8-520e1-52627cf709a95.design.webflow.com | Source site in Webflow}
 */
export function TestimonialCard({
  avatarImage = "https://cdn.prod.website-files.com/6a99efd3a343bee81949ede1/6a99efd3a343bee81949ee29_chermiti-mohamed-HIdwoWg3psQ-unsplash.webp",
  jobTitleText = "Owner, Harbor & Vine",
  nameText = "Elena Ward",
  testimonialText = "“The Mise Lab helped us find the soul of our space. They understood how we wanted guests to feel and translated that into every surface, color, and finish.”",
}: TestimonialCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"testimonial-card"} tag={"div"}>
        <Block className={"text-style-medium"} tag={"div"}>
          {testimonialText}
        </Block>
        <Block className={"testimonial-customer"} tag={"div"}>
          <Block className={"testimonial-customer-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"testimonial-customer-image"}
              height={"auto"}
              loading={"lazy"}
              src={avatarImage}
              width={"auto"}
            />
          </Block>
          <Block className={"testimonial-customer-info"} tag={"div"}>
            <Paragraph className={"testimonial-name-text"}>
              {nameText}
            </Paragraph>
            <Paragraph className={"text-style-regular"}>
              {jobTitleText}
            </Paragraph>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
